name: web-shortlink Actions
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo begin build web-shortlink
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Build
        env:
          GO111MODULE: "auto"
          GOPROXY: "https://proxy.golang.org"
        run: go build .